Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 2048
      Handler: com.simulators.football.StreamLambdaHandler::handleRequest
      CodeUri: .
      Runtime: java21
      Architectures:
        - x86_64
      Events:
        FootBall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY