name: Code Review Verification.

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.md'
      - 'FootballSimulator.drawio.png'
    branches:
      - mainline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw clean package
  test:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run tests and collect coverage
        run: ./mvnw test jacoco:report
      - name: Check code coverage
        run: |
          MINIMUM_COVERAGE=95
          ACTUAL_COVERAGE=$(mvn jacoco:report-aggregate -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -q -Dexec.executable="echo" -Dexec.args='${jacoco.reportPath}' | tr -d '\n')
          echo "Actual coverage: $ACTUAL_COVERAGE%"
          if [ -z "$ACTUAL_COVERAGE" ]; then
            echo "Failed to extract coverage percentage from Maven output."
            exit 1
          fi
          if (( $(echo "$ACTUAL_COVERAGE < $MINIMUM_COVERAGE" | bc -l) )); then
            echo "Code coverage is below the required $MINIMUM_COVERAGE% threshold. Current coverage is $ACTUAL_COVERAGE%."
            exit 1
          else
            echo "Code coverage is $ACTUAL_COVERAGE%, which meets the required $MINIMUM_COVERAGE% threshold."
          fi