name: Code Review Verification.

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.md'
      - 'FootballSimulator.drawio.png'
    branches:
      - mainline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw clean package
  test:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Coverage
        run: ./mvnw test jacoco:report
      - name: jacoco-reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          minimum_coverage: 80
          fail_below_threshold: true
          publish_only_summary: false

            # Publish Coverage Job Summary  # Optional
      - name: Add Jacocoo report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco-reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco-reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco-reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco-reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      - name: Add coverage to PR
        id: jacoco
        uses: juliusiglesia/jacoco-report-publisher@0.0.2
        with:
          report-paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          min-overall-instructions-coverage: 50
          min-overall-branch-coverage: 50
          min-modified-files-instructions-coverage: 70
          min-modified-files-branch-coverage: 70